### PR TITLE
Update proposal to accommodate need for type imports

### PR DESCRIPTION
**Pull request by linclark**
This PR makes some fundamental changes in the way that wasm ES modules will be instantiated. Instead of running [instantiate](https://webassembly.github.io/spec/core/exec/modules.html#instantiation) during the ES module system's instantiation phase.

This change is motivated by work going on to share types between JS and wasm. This will require importing types. Because types defined in JS would only be initialized during evaluation, we need JS modules exporting types to evaluate before the importing wasm module snapshots them.

During the instantiation phase, we create live bindings for every declared export of a wasm module and link to the import memory locations but do not snapshot them yet. Unlike functions in JavaScript, function exports in WebAssembly will not be hoisted and are instead like every other kind of export. They get filled in when you evaluate the module.

During evaluation, the wasm module will take a snapshot of all of its imported bindings and initialize all of its exports. 

I will add an item to the [next CG agenda](https://github.com/WebAssembly/meetings/blob/master/2018/CG-08-21.md) to discuss this further.

### CODE REVIEW

**Comment by rossberg** [comment]
I think this makes sense, provided I interpret it right. There is an unfortunate clash of terminology here. In particular, where the PR speaks of "evaluating a Wasm module" I think it means "instantiating" in Wasm vocabulary, and where it speaks of "instantiating a Wasm module" it means creating the JS side wrapper objects for it(?). Without such a reinterpretation, e.g., it is difficult to assign meaning to statements like

> wasm module is instantiated. All exports are set to undefined.

Would it be possible to clarify these terminology differences and perhaps use less ambiguous words to bridge the two specs involved? For example, instead of "instantiating a module" speak of "defining" it (or some other word not pre-occupied in either spec) and specify what concept that maps to on both sides. Or short of that, at least qualify the ambiguous uses in some suitable fashion.

**Comment by domenic** [comment]
+1 on doing whatever possible to clarify terminology confusion. My initial idea is to never say "instantiate" but instead "wasm-instantiate" / "ES-instantiate". (Same for evaluate?) There may be better ideas though, such as Andreas's suggestion of introducing a third set of words.

**Comment by tschneidereit** [comment]
I wonder if we could change the language in one of the specs. It seems like that'd be possible in the ES spec because the module instantiation phases are internal in that case?

**Comment by linclark** [comment]
Till and I discussed his idea of changing the terminology in the ES spec. I like the idea of using the term "linking" instead of "instantiate". For evaluation, I don't know what an appropriate term would be.

@tschneidereit, do you have a feel for how the committee would receive this?

In the meantime, it is difficult to fully disambiguate this. If the ES spec doesn't change, we will need to have a method in the wasm JS embedding spec called `Instantiate` (which would not perform instantiation as it's defined in the core spec) and another called `Evaluate` (in which the work of `WebAssembly.instantiate` would happen).

**Pull request merged**
